name: Deploy to VPS

# --- Trigger: adjust to taste -----------------------------------------------
on:
  push:           # run after every push to main
    branches: [ "main" ]

# ---------------------------------------------------------------------------

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # (optional) pull the repo locally – not required for the remote command
      - name: Checkout repository
        uses: actions/checkout@v4

      # Connect to the VPS and run the deploy commands
      - name: SSH into server & git pull
        uses: appleboy/ssh-action@v1.0.0         # ↳ lightweight wrapper around ssh
        with:
          host:     ${{ secrets.VPS_HOST }}      # e.g. 203.0.113.10
          username: ${{ secrets.VPS_USER }}      # e.g. ubuntu
          key:      ${{ secrets.VPS_SSH_KEY }}   # your *private* key, base-64 or PEM
          port:     ${{ secrets.VPS_PORT }}      # default 22
          script: |
            cd /var/www/emma-gobin.shost.fr/emma-gobin-portfolio
            git pull --ff-only
